on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@hogiagroup'
    - run: npm ci
    - run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
